# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'playground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for playground
  pod 'Firebase/Core', '~> 5.16.0'
  pod 'Firebase/Messaging', '~> 5.16.0'

end
